
package org.example.proxy;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://WebService.example.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConversionEuroToDh")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConversionEuroToDh", targetNamespace = "http://WebService.example.org/", className = "org.example.proxy.ConversionEuroToDh")
    @ResponseWrapper(localName = "ConversionEuroToDhResponse", targetNamespace = "http://WebService.example.org/", className = "org.example.proxy.ConversionEuroToDhResponse")
    @Action(input = "http://WebService.example.org/BanqueService/ConversionEuroToDhRequest", output = "http://WebService.example.org/BanqueService/ConversionEuroToDhResponse")
    public double conversionEuroToDh(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.example.proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://WebService.example.org/", className = "org.example.proxy.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://WebService.example.org/", className = "org.example.proxy.GetCompteResponse")
    @Action(input = "http://WebService.example.org/BanqueService/getCompteRequest", output = "http://WebService.example.org/BanqueService/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<org.example.proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComptes", targetNamespace = "http://WebService.example.org/", className = "org.example.proxy.GetComptes")
    @ResponseWrapper(localName = "getComptesResponse", targetNamespace = "http://WebService.example.org/", className = "org.example.proxy.GetComptesResponse")
    @Action(input = "http://WebService.example.org/BanqueService/getComptesRequest", output = "http://WebService.example.org/BanqueService/getComptesResponse")
    public List<Compte> getComptes();

}
